# Generated by Django 5.2.3 on 2025-09-22 13:07

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(db_index=True, max_length=40)),
                ('keyword_id', models.IntegerField(db_index=True)),
                ('keyword_name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['mood', '-weight', 'keyword_name'],
                'unique_together': {('mood', 'keyword_id')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.watchlist')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'updated_at'], name='api_watchli_user_id_5216e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='uq_watchlist-user-lower-name'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', 'added_at'], name='api_watchli_watchli_7161ec_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['tmdb_id'], name='api_watchli_tmdb_id_e449af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'tmdb_id')},
        ),
    ]
