# Generated by Django 5.2.3 on 2025-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_watchlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
