# Generated by Django 5.2.3 on 2025-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('watched', 'Watched'), ('dropped', 'Dropped')], default='planned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', 'status'], name='api_watchli_watchli_4f4efb_idx'),
        ),
    ]
