# Generated by Django 5.2.3 on 2025-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_watchlistitem_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['position', '-added_at']},
        ),
        migrations.RemoveIndex(
            model_name='watchlistitem',
            name='api_watchli_watchli_7161ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchlistitem',
            name='api_watchli_watchli_4f4efb_idx',
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('watching', 'Watching'), ('watched', 'Watched'), ('dropped', 'Dropped')], db_index=True, default='planned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', 'position'], name='api_watchli_watchli_424c17_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', 'status', 'position'], name='api_watchli_watchli_13a4e5_idx'),
        ),
    ]
