# Generated by Django 5.2.3 on 2025-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_watchlistitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchlistitem',
            name='api_watchli_watchli_424c17_idx',
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', '-added_at'], name='api_watchli_watchli_0713d2_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', '-position'], name='api_watchli_watchli_397a1e_idx'),
        ),
    ]
