# Generated by Django 5.2.3 on 2025-09-29 11:18

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_watchlistitem_api_watchli_watchli_424c17_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.CharField(default=api.models._room_code, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.room')),
            ],
            options={
                'ordering': ['position', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_watchlists', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='api.watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='WatchRoomVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.roommovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner', 'is_active', 'created_at'], name='api_room_owner_i_2d5978_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['invite_code'], name='api_room_invite__f1dea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='roommovie',
            index=models.Index(fields=['room', 'position'], name='api_roommov_room_id_aa7460_idx'),
        ),
        migrations.AddIndex(
            model_name='roommovie',
            index=models.Index(fields=['room', '-added_at'], name='api_roommov_room_id_aae3b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommovie',
            unique_together={('room', 'tmdb_id')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlistcollaborator',
            unique_together={('watchlist', 'user')},
        ),
        migrations.AddIndex(
            model_name='watchroomvote',
            index=models.Index(fields=['room_movie'], name='api_watchro_room_mo_be980e_idx'),
        ),
        migrations.AddIndex(
            model_name='watchroomvote',
            index=models.Index(fields=['user'], name='api_watchro_user_id_baeb04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchroomvote',
            unique_together={('room_movie', 'user')},
        ),
    ]
