# Generated by Django 5.2.3 on 2025-10-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Random URL-safe token embedded in the verify link.', max_length=64, unique=True)),
                ('sent_to', models.EmailField(help_text='Email address this token was sent to (for audit).', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='After this timestamp the token becomes invalid.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='core_emailv_user_id_1948a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('scratch_codes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP device',
                'verbose_name_plural': 'TOTP devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_confirmed'], name='core_twofac_user_id_d1c38a_idx')],
            },
        ),
    ]
